-- TO USE THIS FILE. RENAME IT TO data.sql & CHANGE NAME TO SOMETHING ELSE AFTER INSERTION

INSERT INTO Product (name, price, description, image_url, availability) VALUES
                                                                            ('Smartphone', 699.99, 'Latest model with advanced features', 'https://example.com/smartphone.jpg', true),
                                                                            ('Laptop', 1299.99, 'High-performance laptop for professionals', 'https://example.com/laptop.jpg', true),
                                                                            ('Wireless Earbuds', 149.99, 'Noise-cancelling wireless earbuds', 'https://example.com/earbuds.jpg', true),
                                                                            ('Smartwatch', 199.99, 'Waterproof smartwatch with heart rate monitor', 'https://example.com/smartwatch.jpg', true),
                                                                            ('4K TV', 999.99, 'Ultra HD 4K TV with HDR support', 'https://example.com/4ktv.jpg', true),
                                                                            ('Gaming Console', 499.99, 'Next-gen gaming console with stunning graphics', 'https://example.com/console.jpg', true),
                                                                            ('Bluetooth Speaker', 79.99, 'Portable Bluetooth speaker with deep bass', 'https://example.com/speaker.jpg', true),
                                                                            ('Tablet', 399.99, 'High-resolution tablet for entertainment and work', 'https://example.com/tablet.jpg', true),
                                                                            ('Digital Camera', 599.99, 'Professional digital camera with 4K video recording', 'https://example.com/camera.jpg', true),
                                                                            ('Fitness Tracker', 49.99, 'Fitness tracker with step counter and sleep monitor', 'https://example.com/fitnesstracker.jpg', true),
                                                                            ('Wireless Mouse', 29.99, 'Ergonomic wireless mouse with adjustable DPI', 'https://example.com/mouse.jpg', true),
                                                                            ('Mechanical Keyboard', 89.99, 'Mechanical keyboard with RGB backlighting', 'https://example.com/keyboard.jpg', true),
                                                                            ('External Hard Drive', 119.99, '2TB external hard drive with USB 3.0', 'https://example.com/harddrive.jpg', true),
                                                                            ('Drone', 799.99, 'Quadcopter drone with 4K camera and GPS', 'https://example.com/drone.jpg', true),
                                                                            ('VR Headset', 299.99, 'Virtual reality headset with immersive experience', 'https://example.com/vrheadset.jpg', true),
                                                                            ('Smart Light Bulb', 19.99, 'Wi-Fi enabled smart light bulb with app control', 'https://example.com/lightbulb.jpg', true),
                                                                            ('Electric Toothbrush', 39.99, 'Rechargeable electric toothbrush with multiple modes', 'https://example.com/toothbrush.jpg', true),
                                                                            ('Robot Vacuum', 249.99, 'Automatic robot vacuum cleaner with smart mapping', 'https://example.com/vacuum.jpg', true),
                                                                            ('Action Camera', 199.99, 'Waterproof action camera with 4K video', 'https://example.com/actioncamera.jpg', true),
                                                                            ('Smart Thermostat', 129.99, 'Smart thermostat with remote control and energy saving', 'https://example.com/thermostat.jpg', true);

INSERT INTO User (createdat, default_phone_number, email, first_name, last_name, modifiedat, password) VALUES
                                                                                                           (NOW(6), 1234567890, 'john.doe@example.com', 'John', 'Doe', NOW(6), 'password123'),
                                                                                                           (NOW(6), 2345678901, 'jane.smith@example.com', 'Jane', 'Smith', NOW(6), 'password456'),
                                                                                                           (NOW(6), 3456789012, 'michael.jones@example.com', 'Michael', 'Jones', NOW(6), 'password789'),
                                                                                                           (NOW(6), 4567890123, 'emily.johnson@example.com', 'Emily', 'Johnson', NOW(6), 'password101'),
                                                                                                           (NOW(6), 5678901234, 'david.brown@example.com', 'David', 'Brown', NOW(6), 'password202'),
                                                                                                           (NOW(6), 6789012345, 'sarah.davis@example.com', 'Sarah', 'Davis', NOW(6), 'password303'),
                                                                                                           (NOW(6), 7890123456, 'james.miller@example.com', 'James', 'Miller', NOW(6), 'password404'),
                                                                                                           (NOW(6), 8901234567, 'ashley.wilson@example.com', 'Ashley', 'Wilson', NOW(6), 'password505'),
                                                                                                           (NOW(6), 9012345678, 'christopher.moore@example.com', 'Christopher', 'Moore', NOW(6), 'password606'),
                                                                                                           (NOW(6), 1123456789, 'amanda.taylor@example.com', 'Amanda', 'Taylor', NOW(6), 'password707'),
                                                                                                           (NOW(6), 2234567890, 'joshua.anderson@example.com', 'Joshua', 'Anderson', NOW(6), 'password808'),
                                                                                                           (NOW(6), 3345678901, 'megan.thomas@example.com', 'Megan', 'Thomas', NOW(6), 'password909'),
                                                                                                           (NOW(6), 4456789012, 'daniel.jackson@example.com', 'Daniel', 'Jackson', NOW(6), 'password010'),
                                                                                                           (NOW(6), 5567890123, 'rebecca.white@example.com', 'Rebecca', 'White', NOW(6), 'password111'),
                                                                                                           (NOW(6), 6678901234, 'andrew.harris@example.com', 'Andrew', 'Harris', NOW(6), 'password212'),
                                                                                                           (NOW(6), 7789012345, 'lauren.martin@example.com', 'Lauren', 'Martin', NOW(6), 'password313'),
                                                                                                           (NOW(6), 8890123456, 'alexander.thompson@example.com', 'Alexander', 'Thompson', NOW(6), 'password414'),
                                                                                                           (NOW(6), 9901234567, 'hannah.garcia@example.com', 'Hannah', 'Garcia', NOW(6), 'password515'),
                                                                                                           (NOW(6), 1012345678, 'ryan.martinez@example.com', 'Ryan', 'Martinez', NOW(6), 'password616'),
                                                                                                           (NOW(6), 1212345678, 'olivia.robinson@example.com', 'Olivia', 'Robinson', NOW(6), 'password717');